version: "2.4"

services:
  db:
    image: mysql:5.6
    restart: always
    container_name: dacdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dacdb
    ports:
      - 3308:3306
    volumes:
      - ./data:/var/lib/mysql