version: "2.4"

services:
  db:
    image: mysql:5.6
    container_name: dac4j-demo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dac4jdemodb
    ports:
      - 3308:3306
    volumes:
      - ./data:/var/lib/mysql